name: Package
on:
  release:
    types: [published]
  watch:
    types: [started]

jobs:
  one:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      -
        name: Set up Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '15.0.1'
      -
        name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          FILECLOUD_VERSION: ${{github.ref}}
      -
        name: Build
        run: |
          npm i
          npm run build
      - 
        name : Package release
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: ngx-admin
          path: ./dist
